name: List Files to JSON

on:
  push:
    branches:
      - main

jobs:
  list_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in directory
        id: list_files
        run: |
          FILES=$(ls -1 src/public/assets/images | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "files=$FILES" >> $GITHUB_ENV

      - name: Save JSON array to file
        run: |
          mkdir -p assets
          echo $files > src/public/assets/files.json

      - name: Commit files.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/public/assets/files.json
          git commit -m "Add files.json"
          git push
