name: List Files to JSON

on:
  push:
    branches:
      - main

jobs:
  list_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in directory
        id: list_files
        run: |
          FILES=$(ls src/public/assets/images)
          echo "files=$FILES" >> $GITHUB_ENV

      - name: Create JSON array
        id: create_json
        run: |
          FILES_ARRAY=$(echo $files | jq -R 'split(" ")')
          echo "files_array=$FILES_ARRAY" >> $GITHUB_ENV

      - name: Save JSON array to file
        run: |
          echo $files_array > files.json
          
      - name: Upload JSON file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: files-json
          path: files.json
