name: List Files to JSON

on:
  push:
    branches:
      - main

jobs:
  list_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in directory
        id: list_files
        run: |
          FILES=$(ls -1 src/public/assets/images | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "files=$FILES" >> $GITHUB_ENV

      - name: Save JSON array to file
        run: |
          echo $files > files.json
          
      - name: Upload JSON file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: files-json
          path: files.json
